# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)
podspec_name = "AppPhotoPicker.podspec"

platform :ios do
    desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch") # we could use __method__.to_s instead of duplicating the name
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    pod_lib_lint(allow_warnings: true)
    version = version_bump_podspec(path: "AppPhotoPicker.podspec",
                                   bump_type: type)
    git_add(path: "AppPhotoPicker.podspec")
    git_commit(path: ["AppPhotoPicker.podspec"],
               message: "#{version} release")
    #add_git_tag(tag: "#{version}")
    push_to_git_remote(
remote: "origin", 
local_branch: "HEAD",  # optional, aliased by "branch", default: "master"
force: true,    # optional, default: false
tags: true     # optional, default: true
)
    #pod_push
  end
end
